
name: Nightly Regression

on:
  schedule:
    # run at 15:33 UTC (23:33 UTC+8)
    - cron: '33 15 * * *'

jobs:
  test-difftest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: |
            cd $GITHUB_WORKSPACE/..
            git config --global url."https://github.com/".insteadOf git@github.com:
            git config --global url."https://".insteadOf git://
            git clone https://github.com/OpenXiangShan/xs-env
            cd $GITHUB_WORKSPACE/../xs-env
            sudo -s ./setup-tools.sh
            source ./setup.sh
            rm -r $GITHUB_WORKSPACE/../xs-env/NutShell/difftest
            rm -r $GITHUB_WORKSPACE/../xs-env/XiangShan/difftest
            cp -r $GITHUB_WORKSPACE $GITHUB_WORKSPACE/../xs-env/NutShell
            cp -r $GITHUB_WORKSPACE $GITHUB_WORKSPACE/../xs-env/XiangShan

      - name: Basic Difftest (NutShell)
        run: |
            cd $GITHUB_WORKSPACE/../xs-env
            source ./env.sh
            rm -r ./NEMU
            git clone https://github.com/OpenXiangShan/NEMU
            cd NEMU
            make riscv64-xs-ref_defconfig
            make
            cd $GITHUB_WORKSPACE/../xs-env/NutShell
            source ./env.sh
            make clean
            make emu EMU_CXX_EXTRA_FLAGS="-DFIRST_INST_ADDRESS=0x80000000"
            ./build/emu -b 0 -e 0 -i ./ready-to-run/microbench.bin

      - name: Difftest with Snapshot
        run: |
            cd $GITHUB_WORKSPACE/../xs-env
            source ./env.sh
            rm -r ./NEMU
            git clone https://github.com/OpenXiangShan/NEMU
            cd NEMU
            make riscv64-xs-ref_defconfig
            make
            cd $GITHUB_WORKSPACE/../xs-env/NutShell
            source ./env.sh
            make clean
            make emu EMU_SNAPSHOT=1 EMU_CXX_EXTRA_FLAGS="-DFIRST_INST_ADDRESS=0x80000000"
            ./build/emu -b 0 -e 0 -i ./ready-to-run/microbench.bin
